/**
 * Config, .gitignore, robots.txt, and Dockerfile Template Generator
 * 100% Client-Side generator for project configuration files.
 */

export interface GitignoreTemplate {
  id: string
  name: string
  category: 'languages' | 'frameworks' | 'ides' | 'os' | 'tools'
  rules: string[]
}

export const GITIGNORE_TEMPLATES: GitignoreTemplate[] = [
  // ── Languages & Runtimes ──
  {
    id: 'node',
    name: 'Node.js / npm / pnpm / yarn',
    category: 'languages',
    rules: [
      '# Logs',
      'logs',
      '*.log',
      'npm-debug.log*',
      'yarn-debug.log*',
      'yarn-error.log*',
      'pnpm-debug.log*',
      'lerna-debug.log*',
      '',
      '# Dependencies',
      'node_modules/',
      '.pnp',
      '.pnp.js',
      '',
      '# Cache & Coverage',
      '.npm',
      '.eslintcache',
      '.stylelintcache',
      'coverage/',
      '.nyc_output',
      '',
      '# Environment files',
      '.env',
      '.env.local',
      '.env.development.local',
      '.env.test.local',
      '.env.production.local',
      '*.pem',
    ],
  },
  {
    id: 'python',
    name: 'Python / Poetry / Pipenv',
    category: 'languages',
    rules: [
      '# Byte-compiled / optimized / DLL files',
      '__pycache__/',
      '*.py[cod]',
      '*$py.class',
      '',
      '# Distribution / packaging',
      '.Python',
      'build/',
      'develop-eggs/',
      'dist/',
      'downloads/',
      'eggs/',
      '.eggs/',
      'lib/',
      'lib64/',
      'parts/',
      'sdist/',
      'var/',
      'wheels/',
      '*.egg-info/',
      '.installed.cfg',
      '*.egg',
      '',
      '# Virtual Environments',
      'venv/',
      'env/',
      'ENV/',
      '.venv/',
      'env.bak/',
      'venv.bak/',
      '',
      '# Pytest & Coverage',
      '.pytest_cache/',
      '.coverage',
      'htmlcov/',
      '.mypy_cache/',
    ],
  },
  {
    id: 'go',
    name: 'Go (Golang)',
    category: 'languages',
    rules: [
      '# Binaries for programs and plugins',
      '*.exe',
      '*.exe~',
      '*.dll',
      '*.so',
      '*.dylib',
      '',
      '# Test binary, built with `go test -c`',
      '*.test',
      '',
      '# Output of the go coverage tool',
      '*.out',
      '',
      '# Dependency directory (if using vendoring)',
      'bin/',
      'dist/',
    ],
  },
  {
    id: 'rust',
    name: 'Rust (Cargo)',
    category: 'languages',
    rules: [
      '# Generated by Cargo',
      '# will have compiled start and with all intermediate artifacts',
      '/target',
      '',
      '# These are backup files generated by rustfmt',
      '**/*.rs.bk',
      '',
      '# MSVC Windows builds',
      '*.pdb',
    ],
  },
  {
    id: 'java',
    name: 'Java / Maven / Gradle',
    category: 'languages',
    rules: [
      '# Compiled class file',
      '*.class',
      '',
      '# Log file',
      '*.log',
      '',
      '# Package Files',
      '*.jar',
      '*.war',
      '*.nar',
      '*.ear',
      '*.zip',
      '*.tar.gz',
      '*.rar',
      '',
      '# Maven output',
      'target/',
      'pom.xml.tag',
      'pom.xml.releaseBackup',
      'pom.xml.versionsBackup',
      '',
      '# Gradle output',
      '.gradle/',
      'build/',
    ],
  },

  // ── Frameworks ──
  {
    id: 'nextjs',
    name: 'Next.js',
    category: 'frameworks',
    rules: [
      '# Next.js build output',
      '.next/',
      'out/',
      '',
      '# Production artifacts',
      'build/',
      'dist/',
      '',
      '# Next.js telemetry and cache',
      'next-env.d.ts',
      '.turbo/',
    ],
  },
  {
    id: 'vite',
    name: 'Vite / React / Vue / Svelte',
    category: 'frameworks',
    rules: [
      '# Vite build outputs',
      'dist/',
      'dist-ssr/',
      '*.local',
    ],
  },

  // ── Operating Systems ──
  {
    id: 'macos',
    name: 'macOS (OS X)',
    category: 'os',
    rules: [
      '# General macOS files',
      '.DS_Store',
      '.AppleDouble',
      '.LSOverride',
      '',
      '# Icon must end with two \\r',
      'Icon\r\r',
      '',
      '# Thumbnails and Spotlight',
      '._*',
      '.Spotlight-V100',
      '.Trashes',
    ],
  },
  {
    id: 'windows',
    name: 'Windows',
    category: 'os',
    rules: [
      '# Windows thumbnail cache files',
      'Thumbs.db',
      'Thumbs.db:encryptable',
      'ehthumbs.db',
      'ehthumbs_vista.db',
      '',
      '# Dump file',
      '*.stackdump',
      '',
      '# Folder config file',
      '[Dd]esktop.ini',
      '',
      '# Recycle Bin used on shared network drives',
      '$RECYCLE.BIN/',
    ],
  },

  // ── IDEs & Editors ──
  {
    id: 'vscode',
    name: 'Visual Studio Code',
    category: 'ides',
    rules: [
      '# VS Code settings directory',
      '.vscode/*',
      '!.vscode/settings.json',
      '!.vscode/tasks.json',
      '!.vscode/launch.json',
      '!.vscode/extensions.json',
      '*.code-workspace',
      '',
      '# Local history extension',
      '.history/',
    ],
  },
  {
    id: 'jetbrains',
    name: 'JetBrains (IntelliJ, WebStorm, PyCharm)',
    category: 'ides',
    rules: [
      '# User-specific stuff',
      '.idea/**/workspace.xml',
      '.idea/**/tasks.xml',
      '.idea/**/usage.statistics.xml',
      '.idea/**/dictionaries',
      '.idea/**/shelf',
      '',
      '# File-based project format',
      '*.iws',
      '',
      '# IntelliJ output',
      'out/',
      '.idea/',
    ],
  },
]

export const POPULAR_PRESETS: { id: string; name: string; templateIds: string[] }[] = [
  {
    id: 'nextjs-fullstack',
    name: 'Next.js 15 Fullstack',
    templateIds: ['node', 'nextjs', 'macos', 'windows', 'vscode'],
  },
  {
    id: 'vite-react',
    name: 'React + Vite Frontend',
    templateIds: ['node', 'vite', 'macos', 'windows', 'vscode'],
  },
  {
    id: 'python-fastapi',
    name: 'Python / FastAPI / Django',
    templateIds: ['python', 'macos', 'windows', 'vscode', 'jetbrains'],
  },
  {
    id: 'go-backend',
    name: 'Go Microservice',
    templateIds: ['go', 'macos', 'windows', 'vscode'],
  },
  {
    id: 'rust-cargo',
    name: 'Rust Binary & Library',
    templateIds: ['rust', 'macos', 'windows', 'vscode'],
  },
]

/**
 * Combines selected .gitignore templates into a single cohesive output.
 */
export function generateGitignore(selectedTemplateIds: string[], customRules = ''): string {
  if (selectedTemplateIds.length === 0 && !customRules.trim()) {
    return '# Select templates above or type custom rules to generate .gitignore\n'
  }

  const selectedTemplates = GITIGNORE_TEMPLATES.filter((t) =>
    selectedTemplateIds.includes(t.id)
  )

  const sections: string[] = [
    `# Created by dev-kit.tech .gitignore Generator`,
    `# Stacks included: ${selectedTemplates.map((t) => t.name).join(', ')}`,
    '',
  ]

  const seenRules = new Set<string>()

  selectedTemplates.forEach((template) => {
    sections.push(`### --- ${template.name} --- ###`)
    template.rules.forEach((rule) => {
      if (!rule || rule.startsWith('#')) {
        sections.push(rule)
      } else if (!seenRules.has(rule)) {
        seenRules.add(rule)
        sections.push(rule)
      }
    })
    sections.push('')
  })

  if (customRules.trim()) {
    sections.push(`### --- Custom Project Rules --- ###`)
    sections.push(customRules.trim())
    sections.push('')
  }

  return sections.join('\n').trim() + '\n'
}

/**
 * Generates standard robots.txt content.
 */
export interface RobotsTxtOptions {
  allowAll?: boolean
  disallowPaths?: string[]
  allowPaths?: string[]
  sitemapUrl?: string
  crawlDelay?: number
}

export function generateRobotsTxt(options: RobotsTxtOptions): string {
  const {
    allowAll = true,
    disallowPaths = ['/api/', '/admin/', '/private/'],
    allowPaths = ['/'],
    sitemapUrl = 'https://yourdomain.com/sitemap.xml',
    crawlDelay,
  } = options

  const lines: string[] = [
    '# robots.txt generated by dev-kit.tech',
    'User-agent: *',
  ]

  if (allowAll) {
    allowPaths.forEach((path) => lines.push(`Allow: ${path}`))
    disallowPaths.forEach((path) => lines.push(`Disallow: ${path}`))
  } else {
    lines.push('Disallow: /')
  }

  if (crawlDelay && crawlDelay > 0) {
    lines.push(`Crawl-delay: ${crawlDelay}`)
  }

  if (sitemapUrl && sitemapUrl.trim()) {
    lines.push('')
    lines.push(`Sitemap: ${sitemapUrl.trim()}`)
  }

  return lines.join('\n') + '\n'
}

/**
 * Generates starter multi-stage Dockerfile and docker-compose.yml templates.
 */
export type DockerStack = 'nextjs' | 'node-express' | 'python-fastapi' | 'golang' | 'rust'

export function generateDockerConfig(stack: DockerStack): { dockerfile: string; compose: string } {
  switch (stack) {
    case 'nextjs':
      return {
        dockerfile: `# Multi-stage Next.js Standalone Dockerfile
FROM node:20-alpine AS base
WORKDIR /app
RUN apk add --no-cache libc6-compat

# Install dependencies
FROM base AS deps
COPY package.json pnpm-lock.yaml* package-lock.json* yarn.lock* ./
RUN if [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
    elif [ -f yarn.lock ]; then yarn --frozen-lockfile; \
    else npm ci; fi

# Build the application
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# Production Runner
FROM base AS runner
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000

CMD ["node", "server.js"]`,
        compose: `version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000`,
      }

    case 'python-fastapi':
      return {
        dockerfile: `# Production FastAPI Python Dockerfile
FROM python:3.12-slim AS base
WORKDIR /app
ENV PYTHONUNBUFFERED=1 \\
    PYTHONDONTWRITEBYTECODE=1 \\
    PIP_NO_CACHE_DIR=1

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    curl build-essential && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Run as non-root user
RUN useradd -m appuser && chown -R appuser:appuser /app
USER appuser

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \\
  CMD curl -f http://localhost:8000/health || exit 1

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]`,
        compose: `version: '3.8'

services:
  api:
    build: .
    container_name: fastapi-service
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - PORT=8000`,
      }

    case 'golang':
      return {
        dockerfile: `# Multi-stage Go Binary Dockerfile
FROM golang:1.23-alpine AS builder
WORKDIR /app
RUN apk add --no-cache git ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /server .

# Minimal Distroless / Scratch Runtime
FROM alpine:3.20 AS runner
WORKDIR /app
RUN apk --no-cache add ca-certificates tzdata

COPY --from=builder /server /app/server
USER nobody:nobody
EXPOSE 8080

CMD ["/app/server"]`,
        compose: `version: '3.8'

services:
  app:
    build: .
    container_name: go-service
    restart: unless-stopped
    ports:
      - "8080:8080"`,
      }

    case 'rust':
      return {
        dockerfile: `# Multi-stage Rust Application Dockerfile
FROM rust:1.80-slim AS builder
WORKDIR /app
RUN apt-get update && apt-get install -y pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*

COPY Cargo.toml Cargo.lock ./
COPY src ./src
RUN cargo build --release

# Ultra-slim runtime
FROM debian:bookworm-slim AS runner
WORKDIR /app
RUN apt-get update && apt-get install -y ca-certificates libssl3 && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/my_app /app/my_app
USER 1000:1000
EXPOSE 8080

CMD ["/app/my_app"]`,
        compose: `version: '3.8'

services:
  rust-app:
    build: .
    container_name: rust-app
    ports:
      - "8080:8080"`,
      }

    default: // node-express
      return {
        dockerfile: `# Production Node.js Express Dockerfile
FROM node:20-alpine AS base
WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

EXPOSE 4000
CMD ["node", "src/index.js"]`,
        compose: `version: '3.8'

services:
  api:
    build: .
    container_name: express-api
    restart: unless-stopped
    ports:
      - "4000:4000"`,
      }
  }
}
